#!/bin/bash

DEST=${1:-'/tmp/fred-pdf-examples'}

echo Create folder $DEST
mkdir -p $DEST


echo create file $DEST/advance_invoice_cs.pdf
xsltproc --stringparam lang cs templates/advance_invoice.xsl examples/advance_invoice.xml | ./fred-doc2pdf > $DEST/advance_invoice_cs.pdf

echo create file $DEST/advance_invoice_en.pdf
xsltproc --stringparam lang en templates/advance_invoice.xsl examples/advance_invoice.xml | ./fred-doc2pdf > $DEST/advance_invoice_en.pdf

echo create file $DEST/auth_info_cs.pdf
xsltproc --stringparam lang cs templates/auth_info.xsl examples/auth_info.xml | ./fred-doc2pdf > $DEST/auth_info_cs.pdf

echo create file $DEST/auth_info_en.pdf
xsltproc --stringparam lang en templates/auth_info.xsl examples/auth_info.xml | ./fred-doc2pdf > $DEST/auth_info_en.pdf

echo create file $DEST/contact_verification_auth_owner.pdf
xsltproc templates/contact_verification_auth_owner.xsl examples/contact_verification_auth_owner.xml | ./fred-doc2pdf > $DEST/contact_verification_auth_owner.pdf

echo create file $DEST/defunct_contacts.txt
xsltproc templates/defunct_contacts.xsl examples/warning_letter1.xml | sed 1d > $DEST/defunct_contacts.txt

echo create file $DEST/helios.xml
xsltproc templates/helios.xsl examples/invoice.xml | iconv -f cp1250 | sed 's|windows-1250|utf-8|' | xmllint --format - > $DEST/helios.xml

echo create file $DEST/invoice.pdf
xsltproc templates/invoice.xsl examples/invoice.xml | ./fred-doc2pdf > $DEST/invoice.pdf

echo create file $DEST/mojeid_auth_user.pdf
xsltproc templates/mojeid_auth_owner.xsl examples/mojeid_auth_user.xml | ./fred-doc2pdf > $DEST/mojeid_auth_user.pdf

# test country: Česká republika
echo create file $DEST/mojeid_optys_cz.pdf
xsltproc templates/mojeid_auth_owner_optys.xsl examples/mojeid_auth_owner_optys_cz.xml | ./fred-doc2pdf > $DEST/mojeid_optys_cz.pdf

# test country: CZ
echo create file $DEST/mojeid_optys_cz2.pdf
xsltproc templates/mojeid_auth_owner_optys.xsl examples/mojeid_auth_owner_optys_cz2.xml | ./fred-doc2pdf > $DEST/mojeid_optys_cz2.pdf

# test country: CZECH REPUBLIC
echo create file $DEST/mojeid_optys_cz3.pdf
xsltproc templates/mojeid_auth_owner_optys.xsl examples/mojeid_auth_owner_optys_cz3.xml | ./fred-doc2pdf > $DEST/mojeid_optys_cz3.pdf

# test country: Czech Republic
echo create file $DEST/mojeid_optys_cz4.pdf
xsltproc templates/mojeid_auth_owner_optys.xsl examples/mojeid_auth_owner_optys_cz4.xml | ./fred-doc2pdf > $DEST/mojeid_optys_cz4.pdf

# test country: Slovensko
echo create file $DEST/mojeid_optys_sk.pdf
xsltproc templates/mojeid_auth_owner_optys.xsl examples/mojeid_auth_owner_optys_sk.xml | ./fred-doc2pdf > $DEST/mojeid_optys_sk.pdf

# test country: Česká republika
echo create file $DEST/mojeid_change_optys_cz.pdf
xsltproc templates/mojeid_auth_owner_change_optys.xsl examples/mojeid_auth_owner_optys_cz.xml | ./fred-doc2pdf > $DEST/mojeid_change_optys_cz.pdf

# test country: CZ
echo create file $DEST/mojeid_change_optys_cz2.pdf
xsltproc templates/mojeid_auth_owner_change_optys.xsl examples/mojeid_auth_owner_optys_cz2.xml | ./fred-doc2pdf > $DEST/mojeid_change_optys_cz2.pdf

# test country: CZECH REPUBLIC
echo create file $DEST/mojeid_change_optys_cz3.pdf
xsltproc templates/mojeid_auth_owner_change_optys.xsl examples/mojeid_auth_owner_optys_cz3.xml | ./fred-doc2pdf > $DEST/mojeid_change_optys_cz3.pdf

# test country: Czech Republic
echo create file $DEST/mojeid_change_optys_cz4.pdf
xsltproc templates/mojeid_auth_owner_change_optys.xsl examples/mojeid_auth_owner_optys_cz4.xml | ./fred-doc2pdf > $DEST/mojeid_change_optys_cz4.pdf

# test country: Slovensko
echo create file $DEST/mojeid_change_optys_sk.pdf
xsltproc templates/mojeid_auth_owner_change_optys.xsl examples/mojeid_auth_owner_optys_sk.xml | ./fred-doc2pdf > $DEST/mojeid_change_optys_sk.pdf

echo create file $DEST/mojeid_auth.pdf
xsltproc templates/mojeid_auth_user.xsl examples/mojeid_auth_user.xml | ./fred-doc2pdf > $DEST/mojeid_auth.pdf

echo create file $DEST/mojeid_validate_fyz.pdf
xsltproc templates/mojeid_validate.xsl examples/mojeid_validate_fyz.xml | ./fred-doc2pdf > $DEST/mojeid_validate_fyz.pdf

echo create file $DEST/mojeid_validate_prav.pdf
xsltproc templates/mojeid_validate.xsl examples/mojeid_validate_prav.xml | ./fred-doc2pdf > $DEST/mojeid_validate_prav.pdf

# test sex:     male
# test state:   validated
# test country: CZ
echo create file $DEST/mojeid_card_optys_m_v_cz.pdf
xsltproc templates/mojeid_card_optys.xsl examples/mojeid_card_optys_m_v_cz.xml | ./fred-doc2pdf > $DEST/mojeid_card_optys_m_v_cz.pdf

# test sex:     male
# test country: CZ
echo create file $DEST/mojeid_card_optys_m_cz.pdf
xsltproc templates/mojeid_card_optys.xsl examples/mojeid_card_optys_m_cz.xml | ./fred-doc2pdf > $DEST/mojeid_card_optys_m_cz.pdf

# test sex:     female
# test state:   validated
# test country: SK
echo create file $DEST/mojeid_card_optys_f_v_sk.pdf
xsltproc templates/mojeid_card_optys.xsl examples/mojeid_card_optys_f_v_sk.xml | ./fred-doc2pdf > $DEST/mojeid_card_optys_f_v_sk.pdf

# test sex:     female
# test country: SK
echo create file $DEST/mojeid_card_optys_f_sk.pdf
xsltproc templates/mojeid_card_optys.xsl examples/mojeid_card_optys_f_sk.xml | ./fred-doc2pdf > $DEST/mojeid_card_optys_f_sk.pdf

echo create file $DEST/public_request_block_en.pdf
xsltproc templates/public_request.xsl examples/public_request_block.xml | ./fred-doc2pdf > $DEST/public_request_block_en.pdf

echo create file $DEST/public_request_block_cs.pdf
xsltproc --stringparam lang cs templates/public_request.xsl examples/public_request_block.xml | ./fred-doc2pdf > $DEST/public_request_block_cs.pdf

echo create file $DEST/public_request_unblock_en.pdf
xsltproc templates/public_request.xsl examples/public_request_unblock.xml | ./fred-doc2pdf > $DEST/public_request_unblock_en.pdf

echo create file $DEST/public_request_unblock_cs.pdf
xsltproc --stringparam lang cs templates/public_request.xsl examples/public_request_unblock.xml | ./fred-doc2pdf > $DEST/public_request_unblock_cs.pdf

echo create file $DEST/public_request_authinfo_en.pdf
xsltproc templates/public_request.xsl examples/public_request_authinfo.xml | ./fred-doc2pdf > $DEST/public_request_authinfo_en.pdf

echo create file $DEST/public_request_authinfo_cs.pdf
xsltproc --stringparam lang cs templates/public_request.xsl examples/public_request_authinfo.xml | ./fred-doc2pdf > $DEST/public_request_authinfo_cs.pdf

echo create file $DEST/warning_letter1.pdf
xsltproc templates/warning_letter.xsl examples/warning_letter1.xml | ./fred-doc2pdf > $DEST/warning_letter1.pdf

echo create file $DEST/warning_letter2.pdf
xsltproc templates/warning_letter.xsl examples/warning_letter2.xml | ./fred-doc2pdf > $DEST/warning_letter2.pdf

echo create file $DEST/notice_to_correct_data.pdf
xsltproc templates/notice_to_correct_data.xsl examples/notice_to_correct_data.xml | ./fred-doc2pdf > $DEST/notice_to_correct_data.pdf

echo create file $DEST/confirm_correction.pdf
xsltproc templates/confirm_correction.xsl examples/notice_to_correct_data.xml | ./fred-doc2pdf > $DEST/confirm_correction.pdf

echo create file $DEST/confirm_correction_cz.pdf
xsltproc templates/confirm_correction.xsl examples/notice_to_correct_data_cz.xml | ./fred-doc2pdf > $DEST/confirm_correction_cz.pdf

echo create file $DEST/notice_to_correct_data_long_address.pdf
xsltproc templates/notice_to_correct_data.xsl examples/notice_to_correct_data_long_address.xml | ./fred-doc2pdf > $DEST/notice_to_correct_data_long_address.pdf

echo create file $DEST/confirm_correction_long_address.pdf
xsltproc templates/confirm_correction.xsl examples/notice_to_correct_data_long_address.xml | ./fred-doc2pdf > $DEST/confirm_correction_long_address.pdf

echo create file $DEST/record_statement_keyset.pdf
xsltproc --stringparam testsignature yes templates/record_statement_keyset.xsl examples/record_statement_keyset.xml | ./fred-doc2pdf > $DEST/record_statement_keyset.pdf

echo create file $DEST/record_statement_nsset.pdf
xsltproc --stringparam testsignature yes templates/record_statement_nsset.xsl examples/record_statement_nsset.xml | ./fred-doc2pdf > $DEST/record_statement_nsset.pdf

echo create file $DEST/record_statement_domain.pdf
xsltproc --stringparam testsignature yes templates/record_statement_domain.xsl examples/record_statement_domain.xml | ./fred-doc2pdf > $DEST/record_statement_domain.pdf

echo create file $DEST/record_statement_contact.pdf
xsltproc --stringparam testsignature yes templates/record_statement_contact.xsl examples/record_statement_contact.xml | ./fred-doc2pdf > $DEST/record_statement_contact.pdf

echo create file $DEST/record_statement_contact_partially_closed.pdf
xsltproc --stringparam testsignature yes templates/record_statement_contact.xsl examples/record_statement_contact_partially_closed.xml | ./fred-doc2pdf > $DEST/record_statement_contact_partially_closed.pdf

echo create file $DEST/record_statement_contact_not_linked.pdf
xsltproc --stringparam testsignature yes templates/record_statement_contact.xsl examples/record_statement_contact_not_linked.xml | ./fred-doc2pdf > $DEST/record_statement_contact_not_linked.pdf

echo create file $DEST/record_statement_contact_private.pdf
sed 's/is_private_printout="false"/is_private_printout="true"/1' examples/record_statement_contact.xml | xsltproc --stringparam testsignature yes templates/record_statement_contact.xsl - | ./fred-doc2pdf > $DEST/record_statement_contact_private.pdf

echo create file $DEST/record_statement_contact_partially_closed_private.pdf
sed 's/is_private_printout="false"/is_private_printout="true"/1' examples/record_statement_contact_partially_closed.xml | xsltproc --stringparam testsignature yes templates/record_statement_contact.xsl - | ./fred-doc2pdf > $DEST/record_statement_contact_partially_closed_private.pdf

echo create file $DEST/record_statement_contact_not_linked_private.pdf
sed 's/is_private_printout="false"/is_private_printout="true"/1' examples/record_statement_contact_not_linked.xml | xsltproc --stringparam testsignature yes templates/record_statement_contact.xsl - | ./fred-doc2pdf > $DEST/record_statement_contact_not_linked_private.pdf
